### ISSUE TITLE
Recovery the "Group" fearture

### ISSUE THREAD

**Issue by riverstore** [mifune/gazelle#13]
Hi! I really love this modify but I also love the the "Group" feature. I want to "recovery" it, but I don't know where to start. Can anyone please give me a tip. Thanks a lot

**Comment by mifune** [comment]
it won't be that easy I'm afraid. But, at least the torrent_group and torrents tables are still separate!

I would suggest looking at a version of gazelle (like RC2) that still has groups and comparing specific pages. The main pages to be affected are going to be in the /torrents section and the /upload section. torrents/details.php & upload/upload.php + /upload_handle.php is probably a good place to start but there will be numerous pages affected. You will probably end up finding them all by trial and error if a systematic search doesn't turn them all up. 

I can tell you there is at least one place where the code assumes that torrentid and groupid are the same (apart from the upload handler) - iirc its in reportsv2, that will need to sorted out properly as when you use groups those numbers are no longer synonymous. 

Good luck! I will be interested to see how you get on, there have been several user requests for us to add groups back in but realistically I won't be looking to do that until next year at the earliest.

**Comment by riverstore** [comment]
Thanks a lot for responding, I used to compare this mod with RC2 as you talk, and I found that there are lots of differences. It look like that, we have to add a Quality property or something similar for torrent. And it's really hard to me so I ask for help here. I think, I should wait for you ^^

PS: If you have more freetime, please give me more informations, I hope I can do something
