### ISSUE TITLE
Bonus system.

### ISSUE THREAD

**Issue by WUKONS** [mifune/gazelle#14]
You are the man, script_start stuff helped to get it working +/- properly. :)
Thanks.
btw. EMP using double upload for all torrents? 
And only half size for download? Or I'm mistaking something.
Thanks.

**Comment by WUKONS** [comment]
Got badges up too.
Articles bitching. 

And yes, still that question about double up and half down are actual.
Thanks this code rocks, was started thinking about moving on this code, but after got these tut's working, there is no stepping back anymore. :)

**Comment by mifune** [comment]
re: 'double up half down' I am not exactly sure what you mean?

a doubleseed slot should give you double up counted, apart from that (and FL being none counted) that should be it. There was some issue in the past with slots in the tracker but iirc its sorted now.

**Comment by WUKONS** [comment]
Oh, it's like that, I though double seeding are all the time. If it's done for Slot, it shouldn't be hard to enable for all tracker? Can you please point me on the right direction? And with half down I mean't that counts only 1/2 (50%) of downloaded torrent size like Silver torrent or something. And if that can be done, I will be more than happy. 
Waiting for comments. Thanks.

**Comment by WUKONS** [comment]
One more thing, the Credit shop acting strange. I don't know it's a bug on code or just my fault. When user download stats are 0.00B then you can't buy action to remove GB's, but after downloading any amount you are available to buy all actions for removing GB's. Like, you downloaded 1GB but you are able to buy -10GB item.

**Comment by mifune** [comment]
I am not sure if you mean 'personal doubleseed' (ie. like personal FL, everything is FL for a user) or 'sitewide doubleseed' ie. doubleseed for everyone. Neither is implemented for doubleseed, but if you look at how they are done for freeleech you might be able to extend it to doubleseed but it would need changes in ocelot as well (and a flag in the db site_options table or something to track site doubleseed status, or a var in the user table to track personal doubleseed).

There is no 'half-leech' option. You could add it, there is a neutral leech option (which we don't use so is not selectable in the interface but all the plumbing should still be there for that) also. Again if you want to add this it will need changes in ocelot (to actually apply it to the up/down data as it comes in to the tracker).

re: the bonus shop, I think you are right, it doesn't do a clever check there (just a simple one). It seems to work out okay on emp and we have a large todo list already so there is no urgency to improve this.

**Comment by WUKONS** [comment]
Alright, thanks for info.
Will try to blow up Ocelot with 'sitewide doubleseed'.

Okay, 'sitewide doubleseed' sounds easier than 'half-leech' so i will stick with 'sitewide doubleseed'. ;D
Thanks.

Yeah, that sure not that important but members losing they'r points in that way.

**Comment by WUKONS** [comment]
Just found time to look into it, got it working smoothly. :)
