### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by elaur** [mifune/gazelle#15]
Hi,

Just want to open an small private tracker and i want to use gazelle source, do you know an torrent site which use mifune/gazelle ?

**Comment by WUKONS** [comment]
I'm going to move on mifune next week, tested played with it, works pretty neath. :)

Sincerely: WUKONS

Date: Sun, 20 Oct 2013 04:19:54 -0700

**Comment by lun4r** [comment]
Very good engine, with those seedbonus features, etc...
But i can't build modified ocelot tracker on CentOS.
So - i am using original gazelle tracker now.
Name of tracker using this engine is similar to default skin name.
I believe you found it)

**Comment by WUKONS** [comment]
Why not switch to Debian?

Sincerely: WUKONS

Date: Sun, 20 Oct 2013 11:25:08 -0700

**Comment by lun4r** [comment]
Cause it was already running server with many sites

**Comment by elaur** [comment]
@WUKONS your recover pass system is broken.

**Comment by WUKONS** [comment]
@melaur thanks, but for me and recent testers all fine. might be your mail. :p
