### ISSUE TITLE
Error in privateheader.php

### ISSUE THREAD

**Issue by lun4r** [mifune/gazelle#2]
Error on this page:

MySQL: Invalid Query: SELECT COUNT(s.TopicID)
                FROM users_subscriptions AS s
                        JOIN forums_last_read_topics AS l ON s.UserID = l.UserID AND s.TopicID = l.TopicID
                        JOIN forums_topics AS t ON l.TopicID = t.ID
                        JOIN forums AS f ON t.ForumID = f.ID
                WHERE (f.MinClassRead <=  OR f.ID IN (''))
                        AND l.PostID < t.LastPostID
                        AND s.UserID = 1 SQL error: 1064 (You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'OR f.ID IN (''))
                        AND l.PostID < t.LastPostID
           ' at line 6)

**Comment by mifune** [comment]
for some reason $LoggedUser['Class'] is not set - perhaps the permissions table isnt set up yet?

$LoggedUser['Class'] is the permission level of the current user, the sql should be : 

WHERE (f.MinClassRead <=[permissionlevel] OR f.ID IN (''))
